export class Constants {
    public static ROUTES = {
        IMAGE_UPLOAD : 'image_upload',
        IMAGE_UPLOAD_CLOUD : 'image_upload_cloud',
        VERIFY_CAPTCHA : 'verify_captcha',
        USER_SIGNUP : 'user_signup',
        USER_LOGIN : 'user_login',
        USER_FORGOT_PWD : 'user_forgot_pwd',
        USER_PROFILE : 'user_profile',
        USER_BY_NAME : 'get_user_by_name',
        USER_UPDATE_PROFILE : 'edit_user_profile',
        ADD_NEW_POST : 'add_new_post',
        GET_ALL_POSTS : 'get_all_posts',
        POST_LIKED : 'post_liked',
        POST_COMMENT : 'post_comment',
        GET_ALL_COMMENTS : 'get_all_comments',
        GET_ALL_USERS : 'get_all_users',
        FOLLOW_USER : 'follow_user',
        GET_SINGLE_USERS : 'get_single_user',
        UNFOLLOW_USER : 'unfollow_user',
        CLEAR_NOTIFICATION : 'clear_notification',
        MARK_ALL_NOTIFICATION : 'mark_all_notification',
        SEND_CHAT_MSG : 'send_chat_message',
        GET_CHAT_MSG : 'get_chat_message',
        MARK_CHAT_MSGS : 'mark_chat_messages',
        MARK_ALL_CHAT_MSG : 'mark_all_chat_messages',
        PAYMENT_CHECKOUT : 'payment_checkout',
        PAYTM_PAYMENT_CHECKOUT : 'patym_payment_checkout',
        PAYMENT_SUCCESS : 'payment_success',
        SEND_OTP : 'send_otp',
        CANCEL_OTP_REQ : 'cancel_otp_req',
        VERIFY_OTP : 'verify_otp',
        FILTER_FOLLOWER : 'filter_follower'
    };
}
